#!/bin/bash
# EduRisk AI - Project Cleanup Script (Bash)
# This script removes unnecessary files and folders to reduce project size
# Run this script from the project root directory

echo "========================================"
echo "  EduRisk AI - Project Cleanup"
echo "========================================"
echo ""

# Ask for confirmation
echo "This script will delete:"
echo "  - Test coverage reports (htmlcov, .coverage, .pytest_cache)"
echo "  - Redundant documentation files"
echo "  - Task implementation summaries"
echo "  - Test files (backend/test_*.py)"
echo "  - Unused Docker files"
echo "  - Build artifacts (.next, __pycache__)"
echo "  - Empty placeholder files (.gitkeep)"
echo ""
echo "Estimated space to be freed: 300-500 MB"
echo ""

read -p "Do you want to continue? (yes/no): " confirmation
if [ "$confirmation" != "yes" ] && [ "$confirmation" != "y" ]; then
    echo "Cleanup cancelled."
    exit 0
fi

echo ""
echo "Starting cleanup..."
echo ""

deleted_count=0

# Function to safely delete files/folders
remove_safe_item() {
    local path=$1
    local description=$2
    
    if [ -e "$path" ]; then
        if rm -rf "$path" 2>/dev/null; then
            echo "[OK] Deleted: $description"
            return 0
        else
            echo "[ERROR] Failed to delete: $description"
            return 1
        fi
    else
        echo "[SKIP] Not found: $description"
        return 2
    fi
}

# 1. Delete test coverage reports
echo "1. Removing test coverage reports..."
remove_safe_item "htmlcov" "HTML coverage reports" && ((deleted_count++))
remove_safe_item ".coverage" "Coverage data file" && ((deleted_count++))
remove_safe_item ".pytest_cache" "Pytest cache" && ((deleted_count++))

# 2. Delete redundant documentation
echo ""
echo "2. Removing redundant documentation..."
docs=(
    "DOCKER_FIXES_SUMMARY.md"
    "DOCKER_QUICKSTART.md"
    "RUN_LOCALLY.md"
    "STARTUP_INFO.md"
    "GITIGNORE_SUMMARY.md"
    "GITIGNORE_UPDATE_LOG.md"
    "GIT_SETUP.md"
    "GIT_TRACKING_GUIDE.md"
    "PROJECT_STATUS.md"
    "SETUP.md"
    ".github/GITIGNORE_QUICK_REFERENCE.md"
)
for doc in "${docs[@]}"; do
    remove_safe_item "$doc" "Documentation: $doc" && ((deleted_count++))
done

# 3. Delete task implementation summaries
echo ""
echo "3. Removing task implementation summaries..."
task_files=(
    "TASK_24_IMPLEMENTATION_SUMMARY.md"
    "TASK_26_INTEGRATION_SUMMARY.md"
    "backend/TASK_14_SUMMARY.md"
    "backend/TASK_16_IMPLEMENTATION_SUMMARY.md"
    "backend/TASK_17_IMPLEMENTATION_SUMMARY.md"
    "backend/TASK_18_IMPLEMENTATION_SUMMARY.md"
    "frontend/TASK_20_IMPLEMENTATION_SUMMARY.md"
    "frontend/TASK_21_IMPLEMENTATION_SUMMARY.md"
    "frontend/TASK_23_IMPLEMENTATION_SUMMARY.md"
)
for file in "${task_files[@]}"; do
    remove_safe_item "$file" "Task summary: $file" && ((deleted_count++))
done

# 4. Delete test files
echo ""
echo "4. Removing test files..."
test_files=(
    "backend/demo_config.py"
    "backend/test_config.py"
    "backend/test_config_integration.py"
    "backend/test_endpoints.py"
    "backend/test_error_handling.py"
    "backend/test_rate_limit.py"
    "backend/services/test_risk_calculator.py"
    "test_integration.py"
)
for file in "${test_files[@]}"; do
    remove_safe_item "$file" "Test file: $file" && ((deleted_count++))
done

# 5. Delete unused Docker files
echo ""
echo "5. Removing unused Docker files..."
docker_files=(
    "docker/Dockerfile.frontend.dev"
    "docker/validate-setup.sh"
    "docker-compose.dev.yml"
)
for file in "${docker_files[@]}"; do
    remove_safe_item "$file" "Docker file: $file" && ((deleted_count++))
done

# 6. Delete unused scripts
echo ""
echo "6. Removing unused setup scripts..."
scripts=(
    "quickstart.ps1"
    "quickstart.sh"
    "setup.sh"
)
for script in "${scripts[@]}"; do
    remove_safe_item "$script" "Script: $script" && ((deleted_count++))
done

# 7. Delete example configs
echo ""
echo "7. Removing unused example configs..."
remove_safe_item "backend/config.example.json" "Example config" && ((deleted_count++))

# 8. Delete build artifacts
echo ""
echo "8. Removing build artifacts (will be regenerated by Docker)..."
remove_safe_item "frontend/.next" "Next.js build output" && ((deleted_count++))
remove_safe_item "frontend/node_modules" "Node modules" && ((deleted_count++))
remove_safe_item "frontend/tsconfig.tsbuildinfo" "TypeScript build info" && ((deleted_count++))
remove_safe_item "backend/__pycache__" "Backend Python cache" && ((deleted_count++))
remove_safe_item "ml/__pycache__" "ML Python cache" && ((deleted_count++))

# 9. Delete empty placeholder files
echo ""
echo "9. Removing empty placeholder files..."
gitkeeps=(
    "backend/.gitkeep"
    "docker/.gitkeep"
    "ml/.gitkeep"
)
for file in "${gitkeeps[@]}"; do
    remove_safe_item "$file" "Placeholder: $file" && ((deleted_count++))
done

# 10. Optional: Delete spec files (commented out by default)
echo ""
echo "10. Spec files (SKIPPED - uncomment in script to delete)..."
# Uncomment the lines below if you want to delete spec files
# remove_safe_item ".kiro/specs" "Spec directory" && ((deleted_count++))
# remove_safe_item "Eduriskai kiro techspec.md" "Original spec document" && ((deleted_count++))

# Summary
echo ""
echo "========================================"
echo "  Cleanup Complete!"
echo "========================================"
echo ""
echo "Items deleted: $deleted_count"
echo ""
echo "Your project is now cleaner!"
echo ""
echo "Note: Build artifacts (.next, node_modules, __pycache__) will be"
echo "regenerated automatically when you run 'docker-compose up --build'"
echo ""
